service: energy-monitor-front

provider:
    name: aws
    runtime: nodejs20.x
    profile: default
    region: us-west-2

plugins:
    - serverless-s3-sync

custom:
    bucketName: energy-monitor-front-bucket
    s3Sync:
        - bucketName: ${self:custom.bucketName}
          localDir: build/

resources:
  Resources:
    FrontPageWebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
    FrontPageWebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref FrontPageWebsiteBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: 
                Fn::Join:
                  - /
                  - - Fn::GetAtt:
                        - FrontPageWebsiteBucket
                        - Arn
                    - '*'
              Principal:
                CanonicalUser: 
                  Fn::GetAtt: 
                    - FrontPageWebsiteOriginAccessIdentity
                    - S3CanonicalUserId
    FrontPageWebsiteOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: Origin Access Identity to Access Website Bucket
    FrontPageCloudFront:
      Type: AWS::CloudFront::Distribution
      DependsOn:
        - FrontPageWebsiteBucket
      Properties:
        DistributionConfig: 
          Origins:
            - DomainName: 
                Fn::GetAtt: 
                  - FrontPageWebsiteBucket
                  - RegionalDomainName
              Id: S3Origin
              S3OriginConfig:
                OriginAccessIdentity: 
                  Fn::Join: 
                    - /
                    - - origin-access-identity
                      - cloudfront
                      - !Ref FrontPageWebsiteOriginAccessIdentity
          CustomErrorResponses:
            - ErrorCachingMinTTL: 0
              ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
          Comment: my example website in s3
          DefaultRootObject: index.html
          Enabled: true
          HttpVersion: http2
          PriceClass: PriceClass_All
          ViewerCertificate:
            CloudFrontDefaultCertificate: true